Add Game Server Orchestrator to showcase (team help)
UQComputingSociety/website pull request #227
Opened 2020-10-19 11:21 UTC by Elliot-Alexander

Apologies for the previous pull, apparently I can't read which repo I'm in. Anyway I hope these commits are correct.

2020-10-19 11:45 UTC, bradleysigma requested changes
The showcase images are displayed square. You may want to edit your image to be less long. Also, an image more specific to your project would be better.

2020-10-19 11:45 UTC, bradleysigma commented on content/showcase/_index.html
> +                        src="/img/media/showcase/charon.png"
This should be `/img/media/showcase/game_server.png`

2020-10-19 11:45 UTC, bradleysigma commented on content/showcase/_index.html
> +		    {{< showcase-item
Newest projects should be at the top.

2020-10-19 14:48 UTC, nicklambourne commented
For reference, showcase images are 1000*750px :)

2020-10-19 22:05 UTC, Elliot-Alexander commented
For sure! Will update in a bit and let you know :)

2020-10-21 06:48 UTC, Elliot-Alexander commented
Hey :) have updated the pull. Hopefully this is better :D Let me know

2020-10-21 09:19 UTC, jdcaperon approved these changes
LGTM after conflicts

2020-10-21 10:06 UTC, bradleysigma submitted a review, later dismissed

2020-10-21 10:06 UTC, bradleysigma commented on content/showcase/_index.html
> +                        src="/img/media/showcase/game_server.png"
Please add an underscore to the image file to match this `src`.

2020-10-22 00:44 UTC, Elliot-Alexander commented
God I am so sorry, I so out of it this week. Should hopefully be fixed up now

2020-10-22 05:59 UTC, nicklambourne approved these changes

2020-10-22 06:02 UTC, bradleysigma approved these changes

2020-10-22 06:07 UTC, merged